# Generated by Django 3.1.2 on 2022-11-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='addres',
            new_name='address',
        ),
    ]
