# Generated by Django 4.0.6 on 2022-11-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Category',
            new_name='category',
        ),
    ]
