# Generated by Django 4.1 on 2022-09-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modules_students_remove_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='modules',
            field=models.ManyToManyField(related_name='modules', to='core.modules'),
        ),
    ]
