# Generated by Django 4.1 on 2022-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_expenditure_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
    ]
