# Generated by Django 4.1 on 2022-09-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_remove_expenditure_deleted_at_expenditure_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='is_deleted',
        ),
    ]
