# Generated by Django 3.1.2 on 2022-12-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='아티클',
        ),
    ]
